apiVersion : apps/v1
kind: Deployment
metadata:
    name: my-web
    labels:
       app: my-application
spec:
  replicas: 3
  selector:
    matchLabels:
       project: first-project
  template:
    metadata:
      labels:
       project: first-project
    spec:
      containers:
        - name: my-web
          image: nginx
          ports:
            - containerPort: 80
