apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: test
  labels:
    maintainer: emxtion
spec:
  replicas: 3
  selector:
    matchLabels:
      project: web-site
  template:
    metadata:
      labels:
        project: web-site
    spec:
      containers:
        - name: web-server
          image: emxtion/k8sphp
          ports:
            - containerPort: 80
